# Generated by Django 2.1.3 on 2019-02-01 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='productdiscountitem',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='discount.Discount'),
        ),
        migrations.AddField(
            model_name='productdiscountitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_items', to='discount.Product'),
        ),
    ]
