# Generated by Django 2.1.3 on 2019-02-01 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20190201_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDiscountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_items', to='discount.Brand')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branddiscount', to='discount.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDiscountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_items', to='discount.Category')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorydiscount', to='discount.Discount')),
            ],
        ),
        migrations.AlterField(
            model_name='productdiscountitem',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdiscount', to='discount.Discount'),
        ),
    ]
