# Generated by Django 2.1.3 on 2019-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
